export const CURATED_TAGS = [
  // Styles
  "Photorealistic",
  "Cinematic",
  "Digital Art",
  "Anime",
  "Oil Painting",
  "Watercolor",
  "3D Render",
  "Cyberpunk",
  "Fantasy",
  "Sci-Fi",
  "Minimalist",
  "Abstract",

  // Subjects
  "Portrait",
  "Landscape",
  "Architecture",
  "Character Design",
  "Wildlife",
  "Vehicles",
  "Interior Design",

  // Lighting & Camera
  "Golden Hour",
  "Studio Lighting",
  "Macro",
  "Wide Angle",
  "Bokeh",
  "Volumetric Lighting",

  // Modifiers
  "Masterpiece",
  "High Res",
  "8k",
  "Highly Detailed",

  // Editorial & Aesthetic Styles
  "Editorial",
  "Pinterest",
  "Dreamy",
  "Nostalgic",
  "Cottagecore",
  "Indie",
  "Romantic",
  "Fine Art",
  "Luxury",
  "Fashion",
  "Vintage",
  "Film Photography",
  "Soft Girl",
  "Dreamcore",
  "Ethereal",
  "Moody",
  "Melancholic",
  "Surreal",
  "Floral",
  "Spring",
  "Sunset",
  "Urban",
  "Monochrome",
  "Scrapbook",
  "Moodboard",
  "Magazine Cover",
  "Vogue Style",
  "Analog Film",
  "Wong Kar-wai",
  "Y2K",
  "Korean Editorial",
  "Soft Focus",
  "Film Grain",
  "Long Exposure",
  "Light Painting",
  "Double Exposure",
  "Beach Aesthetic",
  "Countryside",
  "Botanical",
  "Tulip Field",
  "Sunflower Field",
  "Magnolia Garden",
  "Fine Art Portrait",
  "Emotional Storytelling",
  "Luxury Editorial",
  "Indie Cinema"
];
